steps:
# Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/invoice-to-pdf-golang', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/invoice-to-pdf-golang']  
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'server', 
           '--image=us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/invoice-to-pdf-golang', 
           '--region', 'us-central1', '--platform', 'managed', '--no-allow-unauthenticated', 
           '--set-env-vars', 'invoice-to-pdf-output']
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/invoice-to-pdf-golang