steps:
# Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-central1-docker.pkg.dev/scalling-models-stage-async/invoice-to-pdf/invoice-to-pdf-golang', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/scalling-models-stage-async/invoice-to-pdf/invoice-to-pdf-golang']
# Store images in Google Artifact Registry
images:
  - us-central1-docker.pkg.dev/scalling-models-stage-async/invoice-to-pdf/invoice-to-pdf-golang